spring:
  application:
    name: Atividade Multi-Tenant - Luan Augusto.

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    # Faz com que o Hibernate gere SQL otimizado para um DB particular
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql

  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: